# Generated by Django 5.0.1 on 2024-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=100, verbose_name='Наименование Курса')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Картинка')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('name_course',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=100, verbose_name='Наименование Урока')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='Картинка')),
                ('url_video', models.CharField(max_length=200, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('name_course',),
            },
        ),
    ]
