# Generated by Django 5.0.1 on 2024-01-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('name_lesson',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name_course',
            new_name='name_lesson',
        ),
    ]
